# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm install express --save
      - run: npm config set foo:part 3000
      - run: npm install pm2
      - run: npm install syntax-error --save

      # Install ansible
      - run: sudo apt install -y ansible
      - run: git clone https://github.com/stevenstevanus/ansible_circleci.git
      - run: cp ansible_circleci/.ssh/id_rsa* ~/.ssh
      - run: sudo cp ansible_circleci/hosts /etc/ansible/hosts
      - run: cd ansible_circleci
      - run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i development deploy.yml --private-key=~/.ssh/id_rsa -u deploy -vvvv
